export interface SkillCategory {
  name: string;
  skills: string[];
}

export const EXPERT_SKILLS: Record<string, SkillCategory[]> = {
  "Audio": [
    {
      name: "Production Musicale",
      skills: [
        "Ableton Live",
        "FL Studio",
        "Pro Tools",
        "Logic Pro X",
        "Studio One",
        "Cubase",
        "Reason",
        "Composition",
        "Mixage",
        "Mastering",
        "Sound Design",
        "MIDI",
        "Synthèse sonore",
        "Enregistrement",
        "Acoustique",
        "Arrangement",
        "Beatmaking",
        "Sampling",
        "Voix off",
        "Harmonie",
        "Théorie musicale",
        "Production vocale",
        "Mixage multicanal",
        "Automation",
        "Compression",
        "Égalisation",
        "Effets audio",
        "Monitoring"
      ]
    },
    {
      name: "Sound Design",
      skills: [
        "Foley",
        "Bruitage",
        "Post-production audio",
        "Montage son",
        "Design sonore",
        "Spatialisation",
        "Ambiance sonore",
        "Sound FX",
        "Audio immersif",
        "Audio binaural",
        "Synthèse modulaire",
        "Field recording",
        "Sound branding",
        "Audio adaptatif",
        "Audio procédural",
        "Restauration audio",
        "Nettoyage audio",
        "Sound FX design",
        "Mixage 5.1/7.1",
        "Dolby Atmos"
      ]
    },
    {
      name: "Live & Performance",
      skills: [
        "Sonorisation",
        "Table de mixage",
        "Système de diffusion",
        "Régie son",
        "Monitoring de scène",
        "Technicien plateau",
        "Backline",
        "Patch",
        "Balance",
        "Live recording",
        "Régie retours",
        "Façade",
        "Acoustique de salle",
        "Gestion des retours",
        "Installation sonore"
      ]
    }
  ],
  "Vidéo": [
    {
      name: "Montage",
      skills: [
        "Adobe Premiere Pro",
        "Final Cut Pro",
        "DaVinci Resolve",
        "After Effects",
        "Vegas Pro",
        "Avid Media Composer",
        "Motion Design",
        "Color Grading",
        "Transitions",
        "Compositing",
        "Étalonnage",
        "Montage narratif",
        "Montage publicitaire",
        "Montage documentaire",
        "Montage clip",
        "Montage multicam",
        "Habillage vidéo",
        "Titrage",
        "Sous-titrage",
        "Correction colorimétrique",
        "Workflow proxy",
        "Encodage vidéo",
        "Formats d'export",
        "Gestion des médias"
      ]
    },
    {
      name: "Réalisation",
      skills: [
        "Direction artistique",
        "Storyboard",
        "Cadrage",
        "Mise en scène",
        "Direction d'acteurs",
        "Scénarisation",
        "Production",
        "Régie",
        "Lumière",
        "Son plateau",
        "Gestion équipe",
        "Planning tournage",
        "Repérage",
        "Découpage technique",
        "Script",
        "Continuité",
        "Direction photo",
        "Steadicam",
        "Drone",
        "Gestion budget",
        "Casting",
        "Post-production",
        "Supervision VFX"
      ]
    },
    {
      name: "Streaming",
      skills: [
        "OBS Studio",
        "Streamlabs",
        "XSplit",
        "Régie multicam",
        "Streaming live",
        "Gestion des overlays",
        "Modération chat",
        "Interaction viewers",
        "Encodage streaming",
        "Configuration serveur",
        "Gestion des sources",
        "Scènes dynamiques",
        "Transitions live",
        "Intégration médias",
        "Alertes personnalisées"
      ]
    }
  ],
  "Photo": [
    {
      name: "Technique",
      skills: [
        "Photographie numérique",
        "Photographie argentique",
        "Lightroom",
        "Photoshop",
        "Capture One",
        "DxO PhotoLab",
        "Retouche photo",
        "Composition",
        "Éclairage studio",
        "Flash",
        "HDR",
        "Focus stacking",
        "Tirage",
        "Développement RAW",
        "Calibration couleur",
        "Gestion des profils ICC",
        "Photographie HDR",
        "Bracketing",
        "Formats RAW",
        "Workflow studio",
        "Tethering",
        "Retouche beauté",
        "Retouche créative",
        "Photomontage"
      ]
    },
    {
      name: "Spécialités",
      skills: [
        "Portrait",
        "Mode",
        "Mariage",
        "Événementiel",
        "Architecture",
        "Paysage",
        "Macro",
        "Street photography",
        "Reportage",
        "Studio",
        "Nature morte",
        "Culinaire",
        "Sport",
        "Concerts",
        "Photojournalisme",
        "Corporate",
        "Immobilier",
        "Packshot",
        "Aérien",
        "Sous-marine",
        "Astrophotographie",
        "Time-lapse",
        "Light painting"
      ]
    },
    {
      name: "Post-production",
      skills: [
        "Retouche portrait",
        "Retouche beauté",
        "Retouche mode",
        "Compositing",
        "Colorimétrie",
        "Dodge and Burn",
        "Frequency Separation",
        "Retouche créative",
        "Retouche corporate",
        "Photomontage",
        "Masques",
        "Calques",
        "Actions Photoshop",
        "Presets Lightroom",
        "Styles Capture One"
      ]
    }
  ],
  "Design": [
    {
      name: "Graphisme",
      skills: [
        "Adobe Illustrator",
        "Adobe Photoshop",
        "Adobe InDesign",
        "Figma",
        "Sketch",
        "Adobe XD",
        "Affinity Designer",
        "Affinity Photo",
        "Identité visuelle",
        "Logo design",
        "Typographie",
        "Mise en page",
        "Design éditorial",
        "Illustration",
        "Packaging",
        "Motion design",
        "Design print",
        "Branding",
        "Direction artistique",
        "Charte graphique",
        "Design responsive",
        "Iconographie",
        "Illustration vectorielle",
        "Design système"
      ]
    },
    {
      name: "Web/UI",
      skills: [
        "UI Design",
        "UX Design",
        "Responsive design",
        "Prototypage",
        "Wireframing",
        "Design system",
        "Mobile first",
        "Material Design",
        "Design d'interface",
        "Accessibilité",
        "Design mobile",
        "Design web",
        "Atomic Design",
        "Design patterns",
        "Micro-interactions",
        "Design d'icônes",
        "Design d'app",
        "Design de landing page",
        "Design d'emails",
        "Tests utilisateurs",
        "Audit UX",
        "Personas",
        "User flow",
        "Information architecture"
      ]
    },
    {
      name: "Motion Design",
      skills: [
        "After Effects",
        "Cinema 4D",
        "Adobe Animate",
        "Principle",
        "Animation 2D",
        "Animation UI",
        "Character animation",
        "Motion graphics",
        "Transitions animées",
        "Animation logo",
        "Compositing",
        "Expression animation",
        "Storyboard animé",
        "Animation typographique",
        "Animation data"
      ]
    }
  ],
  "3D": [
    {
      name: "Modélisation",
      skills: [
        "Blender",
        "Maya",
        "3ds Max",
        "Cinema 4D",
        "ZBrush",
        "Substance Painter",
        "Substance Designer",
        "Houdini",
        "Hard surface",
        "Organic modeling",
        "Sculpting digital",
        "Texturing",
        "UV mapping",
        "Rigging",
        "Animation 3D",
        "Rendu",
        "Lighting",
        "Modélisation architecturale",
        "Modélisation de personnages",
        "Modélisation de véhicules",
        "Modélisation procédurale",
        "Retopologie",
        "Unwrapping UV",
        "Baking"
      ]
    },
    {
      name: "Animation",
      skills: [
        "Character animation",
        "Motion capture",
        "Simulation physique",
        "VFX",
        "Particules",
        "Dynamique",
        "Animation procédurale",
        "Rendu temps réel",
        "Animation faciale",
        "Stop motion",
        "Animation de foule",
        "Simulation de tissus",
        "Simulation de fluides",
        "Animation keyframe",
        "Animation cycles"
      ]
    },
    {
      name: "Rendu & Compositing",
      skills: [
        "V-Ray",
        "Arnold",
        "Redshift",
        "Octane",
        "Cycles",
        "Eevee",
        "Corona Renderer",
        "RenderMan",
        "Nuke",
        "Fusion",
        "Compositing 3D",
        "Matte painting",
        "HDRI",
        "Éclairage global",
        "Post-production 3D"
      ]
    }
  ],
  "Développement": [
    {
      name: "Front-end",
      skills: [
        "HTML5",
        "CSS3",
        "JavaScript",
        "TypeScript",
        "React",
        "Vue.js",
        "Angular",
        "Svelte",
        "Next.js",
        "Nuxt.js",
        "Sass/SCSS",
        "Tailwind CSS",
        "Bootstrap",
        "Material UI",
        "Responsive Design",
        "Progressive Web Apps",
        "Web Components",
        "State Management",
        "Testing Front-end",
        "Performance Web",
        "Accessibilité Web",
        "SEO",
        "Animation Web",
        "WebGL"
      ]
    },
    {
      name: "Back-end",
      skills: [
        "Node.js",
        "Python",
        "PHP",
        "Java",
        "C#",
        "Ruby",
        "Go",
        "Express.js",
        "Django",
        "Laravel",
        "Spring Boot",
        "ASP.NET",
        "Ruby on Rails",
        "GraphQL",
        "REST API",
        "Base de données SQL",
        "Base de données NoSQL",
        "MongoDB",
        "PostgreSQL",
        "MySQL",
        "Redis",
        "Docker",
        "Kubernetes",
        "AWS"
      ]
    },
    {
      name: "Mobile",
      skills: [
        "React Native",
        "Flutter",
        "Swift",
        "Kotlin",
        "iOS Development",
        "Android Development",
        "Mobile UI/UX",
        "App Store Connect",
        "Google Play Console",
        "Mobile Testing",
        "Mobile Security",
        "Push Notifications",
        "Mobile Analytics",
        "Cross-platform",
        "Native Development"
      ]
    }
  ]
}; 